route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'ansible-webhook'

receivers:
- name: 'ansible-webhook'
  webhook_configs:
    - url: 'http://webhook:5000/webhook'  # Internal Docker DNS (container port 5000)
      send_resolved: true