---
- name: Recover Nginx Service
  hosts: nginx
  tasks:
    - name: Restart Nginx container
      docker_container:
        name: self-healing-infra_nginx_1
        state: restarted
      when: "'NginxDown' in alert.labels.alertname"

    - name: Verify Nginx recovery
      uri:
        url: "http://nginx:80"
        status_code: 200
      register: nginx_verify
      until: nginx_verify.status == 200
      retries: 5
      delay: 2